server:
  port: 8080

spring:

  #  datasource:
  #    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/mcp_demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
  #    username: ${SPRING_DATASOURCE_USERNAME:root}
  #    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  ai:
    ollama:
      base-url: http://ollama:11434
      chat:
        options:
          model: qwen2.5:1.5b
    mcp:
      client:
        #        type: ASYNC
        request-timeout: 60s
        toolcallback:
          enabled: true
        stdio:
          servers-configuration: classpath:/mcp-servers-config-dev.json

logging:
  level:
    org.springframework.ai: DEBUG

